### ISSUE TITLE
User registration/login - intermittent issue

### ISSUE THREAD

**Issue by gdeepchadha** [GITANG1/SE-Yelp#13]
The login is not working properly sometimes. It throws mongo topology error when I try to login. I think this bug can be resolved by handling the db connection close with the query properly using callbacks.

**Comment by srishtihunjan** [comment]
I have created a PR for this bug. It is waiting on everyone's review.

**Comment by srishtihunjan** [comment]
@gdeepchadha this bug has been fixed by the PR "Bug Fix: User registration/login - intermittent issue". PR has been reviewed and closed. Hence marking this bug fixed.
