### ISSUE TITLE
Implement location based search:

### ISSUE THREAD

**Issue by srishtihunjan** [GITANG1/SE-Yelp#38]
- [x] Automatically take user location (using IP?).
 - [x] Take location from user via browser permission.
 - [x] Show "near by" restaurants.
 - [x] Sort restaurants by distance.
 - [x] Schema changes as required

**Comment by gdeepchadha** [comment]
For sorting via distances, distance of restaurant from geolocation has been added from the backend. The front-end needs to sort using this distance field. @GITANG1
