### ISSUE TITLE
Resturant data pertaining to the city should be displayed when the searchbox is empty

### ISSUE THREAD

**Issue by GITANG1** [GITANG1/SE-Yelp#61]
- [x] make restaurant data available when restaurant search is empty

**Comment by srishtihunjan** [comment]
@GITANG1 do we already have a function in place wherein we can look for a restaurant without specifying the location? In this case i'm guessing we just take a default location via IP and search with that.

**Comment by GITANG1** [comment]
@srishtihunjan  by search box I mean restaurant name. Currently restaurant name is mandatory on the back-end for search query. Also, the search query returns null when we only select location and the search box in which we type the restaurant name is empty.
